### ISSUE TITLE
Singularity error

### ISSUE THREAD

**Issue by saramoein372** [zktuong/dandelion#102]
Hi Kelvin,

I am running my Singularity again, but I get this error:

Formating fasta(s) : 0it [00:00, ?it/s]
Assigning genes : 0it [00:00, ?it/s]
Processing data file(s) : 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/share/dandelion_preprocess.py", line 177, in <module>
    main()
  File "/share/dandelion_preprocess.py", line 144, in main
    ddl.pp.reassign_alleles(samples,
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/_preprocessing.py", line 1275, in reassign_alleles
    ] + [filepathlist_heavy[0]] + ['>'] + [
IndexError: list index out of range

Is there any way that I can remove this error? What can be the problem?

Thanks,
Sara

**Comment by saramoein372** [comment]
I also tried this:

 singularity run -B /athena/namlab/scratch/sam4032/BCR /athena/namlab/scratch/sam4032/BCR/sc-dandelion_latest.sif dandelion-preprocess
Formating fasta(s) :   0%|                                                                                                                                                                                                              | 0/11 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/share/dandelion_preprocess.py", line 177, in <module>
    main()
  File "/share/dandelion_preprocess.py", line 104, in main
    ddl.pp.format_fastas(
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/_preprocessing.py", line 306, in format_fastas
    format_fasta(
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/_preprocessing.py", line 84, in format_fasta
    raise OSError(
OSError: Path to fasta file is unknown. Please specify path to fasta file or folder containing fasta file. Starting folder should only contain 1 fasta file.


Again error of directory to fasta file
