### ISSUE TITLE
Singularity error: cannot cache function 'sparse_mean_var_minor_axis'

### ISSUE THREAD

**Issue by crichgriffin** [zktuong/dandelion#198]
### Description of the bug

Tried to run the singularity wrapper after downloading it today, got the error below: 

### Minimal reproducible example

```python
# the public data I am using
curl -O https://cf.10xgenomics.com/samples/cell-vdj/6.1.2/10k_PBMC_TBNK_connect_10k_PBMC_TBNK_connect/10k_PBMC_TBNK_connect_10k_PBMC_TBNK_connect_vdj_b_filtered_contig_annotations.csv
curl -O https://cf.10xgenomics.com/samples/cell-vdj/6.1.2/10k_PBMC_TBNK_connect_10k_PBMC_TBNK_connect/10k_PBMC_TBNK_connect_10k_PBMC_TBNK_connect_vdj_b_filtered_contig.fasta

# 
singularity run -B $PWD sc-dandelion_latest.sif dandelion-preprocess --file_prefix 10k_PBMC_TBNK_connect_10k_PBMC_TBNK_connect_vdj_b_filtered
```

### The error message produced by the code above

```pytb
Traceback (most recent call last):
  File "/share/dandelion_preprocess.py", line 4, in <module>
    import dandelion as ddl
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/__init__.py", line 7, in <module>
    from . import preprocessing as pp
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/__init__.py", line 7, in <module>
    from . import external
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/external/__init__.py", line 7, in <module>
    from ._preprocessing import (
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/external/_preprocessing.py", line 13, in <module>
    import scanpy as sc
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/scanpy/__init__.py", line 14, in <module>
    from . import tools as tl
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/scanpy/tools/__init__.py", line 1, in <module>
    from ..preprocessing import pca
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/scanpy/preprocessing/__init__.py", line 1, in <module>
    from ._recipes import recipe_zheng17, recipe_weinreb17, recipe_seurat
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/scanpy/preprocessing/_recipes.py", line 8, in <module>
    from ._deprecated.highly_variable_genes import (
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/scanpy/preprocessing/_deprecated/highly_variable_genes.py", line 11, in <module>
    from .._utils import _get_mean_var
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/scanpy/preprocessing/_utils.py", line 46, in <module>
    def sparse_mean_var_minor_axis(data, indices, major_len, minor_len, dtype):
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/numba/core/decorators.py", line 212, in wrapper
    disp.enable_caching()
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/numba/core/dispatcher.py", line 863, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/numba/core/caching.py", line 613, in __init__
    self._impl = self._impl_class(py_func)
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/numba/core/caching.py", line 350, in __init__
    raise RuntimeError("cannot cache function %r: no locator available "
RuntimeError: cannot cache function 'sparse_mean_var_minor_axis': no locator available for file '/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/scanpy/preprocessing/_utils.py'
```

**Comment by zktuong** [comment]
hi @crichgriffin, thank you for your interest in `dandelion` and raising this issue. 

I've previously encountered this issue, but can't exactly remember how i dealt with it. It's got to do with `numba` being unable to create its default cache in your compute environment/location when scanpy is being imported.

See here for [default](https://numba.pydata.org/numba-doc/dev/reference/envvars.html) `NUMBA_CACHE_DIR` locations.

Can you try and move to a different location when you have full read/write access (or add sudo to the front of call) and see if that works?

**Comment by ollieeknight** [comment]
Heya,

I also have this same issue. After (I think) fixing by placing a `.numba_config.yaml` in my root directory with `NUMBA_CACHE_DIR=~/scratch/tmp/dandelion`, I now get this next error.

```
Traceback (most recent call last):
  File "/share/dandelion_preprocess.py", line 6, in <module>
    import dandelion as ddl
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/__init__.py", line 2, in <module>
    from dandelion import preprocessing as pp
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/__init__.py", line 2, in <module>
    from dandelion.preprocessing import external
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/external/__init__.py", line 2, in <module>
    from ._preprocessing import (
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/external/_preprocessing.py", line 8, in <module>
    import scanpy as sc
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/scanpy/__init__.py", line 6, in <module>
    from ._utils import check_versions
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/scanpy/_utils/__init__.py", line 28, in <module>
    from .compute.is_constant import is_constant
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/scanpy/_utils/compute/is_constant.py", line 5, in <module>
    from numba import njit
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/numba/__init__.py", line 69, in <module>
    from numba.core import config
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/numba/core/config.py", line 527, in <module>
    _env_reloader = _EnvReloader()
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/numba/core/config.py", line 86, in __init__
    self.reset()
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/numba/core/config.py", line 90, in reset
    self.update(force=True)
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/numba/core/config.py", line 107, in update
    for k, v in y_conf.items():
AttributeError: 'str' object has no attribute 'items'
```
This is my first time running a singularity container, so apologies if I have a naive perspective on things...!

Thanks so much for all of your help!

All the best

Ollie

**Comment by zktuong** [comment]
Hi Ollie,

i think your issue now is that the `.numba_config.yaml` isn't in the format that numba wants:

Not sure how to fix it. perhaps looking at the source code can help:

https://github.com/numba/numba/blob/a4664180ddc91e4c8a37dd06324f4e229a76df91/numba/core/config.py#L135C6-L151

**Comment by milescsmith** [comment]
Found an easy fix.
Create a folder named `tmp` in a location in which you have write permissions.  Probably easiest place is the directory you are running singularity from.  Then, add `--env NUMBA_CACHE_DIR=./tmp` to the singularity command so that it becomes
```
singularity run -B $PWD --env NUMBA_CACHE_DIR=./tmp sc-dandelion_latest.sif dandelion-preprocess
```

If the new directory is somewhere else, you just need to include that location as a bind mount in the command.

**Comment by ollieeknight** [comment]
I've been playing around with it to try and get it work but I can't seem to, I seem to run into issues like those seem before [here ](https://github.com/zktuong/dandelion/issues/199). 

```bash
apptainer run -B $PWD --env NUMBA_CACHE_DIR=./tmp ../sc-dandelion_latest.sif dandelion-preprocess --chain TR
```

```bash
INFO:    underlay of /etc/localtime required more than 50 (83) bind mounts
Matplotlib created a temporary cache directory at /tmp/matplotlib-82ddm1bj because the default path (/data/gpfs-1/users/knighto_c/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Software versions:

dandelion==0.3.4 pandas==2.1.4 numpy==1.26.3 matplotlib==3.8.2 networkx==3.2.1 scipy==1.11.4

Begin preprocessing

command line parameters:
: --------------------------------------------------------------
    --meta = None
    --chain = tr
    --org = human
    --file_prefix = all
    --db = imgt
    --strain = None
    --sep = _
    --flavour = strict
    --filter_to_high_confidence = False
    --keep_trailing_hyphen_number = False
    --skip_format_header = False
    --skip_tigger = False
    --skip_reassign_dj = False
    --skip_correct_c = False
    --clean_output = False
: --------------------------------------------------------------

Formatting fasta(s) :   0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/share/dandelion_preprocess.py", line 378, in <module>
    main()
  File "/share/dandelion_preprocess.py", line 251, in main
    ddl.pp.format_fastas(
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.11/site-packages/dandelion/preprocessing/_preprocessing.py", line 350, in format_fastas
    format_fasta(
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.11/site-packages/dandelion/preprocessing/_preprocessing.py", line 104, in format_fasta
    raise FileNotFoundError(
FileNotFoundError: Path to fasta file is unknown. Please specify path to fasta file or folder containing fasta file. Starting folder should only contain 1 fasta file.
```

I've tried the steps suggested in the previous threads, making a csv file, binding the working directory, all of this. 

```bash
[knighto_c@hpc-cpu-143 dandelion_test_1]$ ls
all_contig_annotations.csv  all_contig.fasta

[knighto_c@hpc-cpu-143 dandelion_test_1]$ ls ..
dandelion_test_1/  logs/  meta.csv  outs/  sc-dandelion_latest.sif/
```

Do you have any suggestions? Hopefully it's a naive one of mine and you see the obvious fix... 

Thank you!

**Comment by ollieeknight** [comment]
I think I got it! for some reason I had to also bind the two folders which contain all of the HPC data. hmmm...

```bash
singularity run -B $PWD,/fast,/data sc-dandelion_latest.sif dandelion-preprocess --chain TR
```

**Comment by zktuong** [comment]
that's bizzare but glad it has worked out! I'll close this issue as there seems to be some fixes for this issue
