### ISSUE TITLE
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()

### ISSUE THREAD

**Issue by colin-leeyc** [zktuong/dandelion#251]
### Description of the bug

Singularity dandelion pre-processing for 10x 5' data (BCR).

Error produces 'filtered_contig_annotations.csv' file, but not 'filtered_contig_dandelion.csv' file.

### Minimal reproducible example

```python
singularity run -B $PWD /lustre/path/to/softwares/dandelion/sc-dandelion_latest.sif dandelion-preprocess \
    --meta="BCR_meta.csv" \
    --file_prefix="filtered" \
    --keep_trailing_hyphen_number \
    --clean_output \
    --skip_format_header
```

### The error message produced by the code above

```pytb
/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/plotnine/ggplot.py:817: PlotnineWarning: Filename: 1087/dandelion/assign_isotype.pdf
Running command: blastn -db /share/database/blast/human/human_BCR_C.fasta -evalue 0.0001 -max_hsps 1 -outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qseq sseq -query 1110_1120/dandelion/filtered_contig.fasta -dust no

Loading 10X annotations

Preparing new calls

Correcting C calls

Traceback (most recent call last):
  File "/share/dandelion_preprocess.py", line 303, in <module>
    main()
  File "/share/dandelion_preprocess.py", line 271, in main
    ddl.pp.assign_isotypes(
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/_preprocessing.py", line 884, in assign_isotypes
    assign_isotype(
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/_preprocessing.py", line 735, in assign_isotype
    dat = _correct_c_call(dat, primers_dict=correction_dict)
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/dandelion/preprocessing/_preprocessing.py", line 627, in _correct_c_call
    if (dat.loc[i, "c_call"] == dat.loc[i, "c_call"]) & (
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.9/site-packages/pandas/core/generic.py", line 1527, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by zktuong** [comment]
Hi Colin, can you confirm for me if there’s duplicate sequence_id or something like that?

the error is saying it doesn’t what to do when there’s multiple True/False to compare

**Comment by colin-leeyc** [comment]
Hi Kelvin,

Yes, indeed there was a duplicate in the 'barcodes' column of the dandelion-reformatted output 'filtered_contig_annotations.csv'. Unsure how this came about but I think this may have thrown the error.

Thank you!
