### ISSUE TITLE
Incompatibility with latest matplotlib

### ISSUE THREAD

**Issue by grst** [zktuong/dandelion#383]
### Description of the bug

This happens in a fresh conda environment with python 3.9 and right after `pip install sc-dandelion`. 
I've seen the error before and it seems to be related to changes in matplotlib. 

```
(test_dandelion) sturm@hochvogel scirpy [fix-cpu-count] % python -c "import dandelion"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sturm/apps/micromamba/envs/test_dandelion/lib/python3.9/site-packages/dandelion/__init__.py", line 5, in <module>
    from dandelion import plotting as pl
  File "/home/sturm/apps/micromamba/envs/test_dandelion/lib/python3.9/site-packages/dandelion/plotting/__init__.py", line 2, in <module>
    from dandelion.plotting._plotting import (
  File "/home/sturm/apps/micromamba/envs/test_dandelion/lib/python3.9/site-packages/dandelion/plotting/_plotting.py", line 31, in <module>
    import dandelion.external.nxviz as nxv
  File "/home/sturm/apps/micromamba/envs/test_dandelion/lib/python3.9/site-packages/dandelion/external/nxviz/__init__.py", line 3, in <module>
    from .api import (
  File "/home/sturm/apps/micromamba/envs/test_dandelion/lib/python3.9/site-packages/dandelion/external/nxviz/api.py", line 10, in <module>
    from dandelion.external.nxviz import edges, nodes
  File "/home/sturm/apps/micromamba/envs/test_dandelion/lib/python3.9/site-packages/dandelion/external/nxviz/edges.py", line 17, in <module>
    from dandelion.external.nxviz import encodings, lines
  File "/home/sturm/apps/micromamba/envs/test_dandelion/lib/python3.9/site-packages/dandelion/external/nxviz/encodings.py", line 10, in <module>
    from matplotlib.cm import get_cmap
ImportError: cannot import name 'get_cmap' from 'matplotlib.cm' (/home/sturm/apps/micromamba/envs/test_dandelion/lib/python3.9/site-packages/matplotlib/cm.py)
```

**Comment by grst** [comment]
Thanks for fixing this so quickly :) 

Allow me one comment regarding version numbers (assuming you follow semver):
 * v0.3.6.post1 should be a patch release and not a post release. Post releases only change documentation, no code. (see https://packaging.python.org/en/latest/specifications/version-specifiers/#post-releases)
 * v0.3.6 should be a minor release and no patch release because it adds new features.
