### ISSUE TITLE
No such file or directory: 'MakeDb_gentle.py'

### ISSUE THREAD

**Issue by hungms** [zktuong/dandelion#387]
### Description of the bug

Hi, thanks again for developing this package - very very helpful. I have recently upgraded the singularity image to run mouse 10X VDJ data. My BCR data runs perfectly with this updated image, however I received the following message when I ran my TCR data : No such file or directory: 'MakeDb_gentle.py'. Please could you help me resolve this issue? Thank you so much!

### Minimal reproducible example

```python
singularity run -B $DATA,$SCRIPT $sif dandelion-preprocess \
	--org mouse \
	--chain TR \
	--db imgt \
	--file_prefix all \
	--meta $SCRIPT/$meta \
	--keep_trailing_hyphen_number \
	--skip_tigger
```

### The error message produced by the code above

```pytb
dandelion==0.3.6 pandas==2.2.2 numpy==1.26.4 matplotlib==3.8.4 networkx==3.3 scipy==1.13.0
Formatting fasta(s) : 100%|██████████| 4/4 [00:03<00:00,  1.23it/s]
Assigning genes :   0%|          | 0/4 [00:00<?, ?it/s]Processing T_4T1.2_LN1/dandelion/all_contig.fasta

Running command: igblastn -germline_db_V /share/database/igblast/database/imgt_mouse_tr_v -germline_db_D /share/database/igblast/database/imgt_mouse_tr_d -germline_db_J /share/database/igblast/database/imgt_mouse_tr_j -auxiliary_data /share/database/igblast/optional_file/mouse_gl.aux -domain_system imgt -ig_seqtype TCR -organism mouse -outfmt 7 std qseq sseq btop -query T_4T1.2_LN1/dandelion/all_contig.fasta -out T_4T1.2_LN1/dandelion/tmp/all_contig_igblast.fmt7 -evalue 0.0001 -min_D_match 9 -D_penalty -4 -c_region_db /share/database/igblast/database/imgt_mouse_tr_c

Running command: igblastn -germline_db_V /share/database/igblast/database/imgt_mouse_tr_v -germline_db_D /share/database/igblast/database/imgt_mouse_tr_d -germline_db_J /share/database/igblast/database/imgt_mouse_tr_j -auxiliary_data /share/database/igblast/optional_file/mouse_gl.aux -domain_system imgt -ig_seqtype TCR -organism mouse -outfmt 19 -query T_4T1.2_LN1/dandelion/all_contig.fasta -out T_4T1.2_LN1/dandelion/tmp/all_contig_igblast.tsv -evalue 0.0001 -min_D_match 9 -D_penalty -4 -c_region_db /share/database/igblast/database/imgt_mouse_tr_c

Running command: MakeDb_gentle.py igblast -i T_4T1.2_LN1/dandelion/tmp/all_contig_igblast.fmt7 -s T_4T1.2_LN1/dandelion/all_contig.fasta -r /share/database/germlines/imgt/mouse/vdj --10x T_4T1.2_LN1/dandelion/all_contig_annotations.csv --extended

Assigning genes :   0%|          | 0/4 [00:54<?, ?it/s]
Traceback (most recent call last):
  File "/share/dandelion_preprocess.py", line 378, in <module>
    main()
  File "/share/dandelion_preprocess.py", line 267, in main
    ddl.pp.reannotate_genes(
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.11/site-packages/dandelion/preprocessing/_preprocessing.py", line 1093, in reannotate_genes
    makedb_igblast(
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.11/site-packages/dandelion/preprocessing/external/_preprocessing.py", line 148, in makedb_igblast
    run(cmd, env=env)  # logs are printed to terminal
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/conda/envs/sc-dandelion-container/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'MakeDb_gentle.py'
```

### OS information

Linux

### Version information

dandelion==0.3.6 pandas==2.2.2 numpy==1.26.4 matplotlib==3.8.4 networkx==3.3 scipy==1.13.0

**Comment by zktuong** [comment]
hi @hungms , thanks for alerting me to this. I'm currently travelling and won't be able to work on this until i'm back at work next week. there's no quick work around this unfortunately as i would need to check that the path to the script is setup correctly in the container.

**Comment by zktuong** [comment]
ok i'm fixing this at #391. once all the tests pass, i will upload a new image (to be called v0.3.7) hopefully by tomorrow.

Thanks for your patience!

**Comment by zktuong** [comment]
ok the image is up! please pull it and let me know if you encounter any further issues.
