### ISSUE TITLE
ImportError with latest AnnData

### ISSUE THREAD

**Issue by grst** [zktuong/dandelion#407]
### Description of the bug

Hi @zktuong, 

it seems like the latest AnnData release broke Dandelion. Some internals got restructured, so the imports from `_core` don't work anymore as before. 

In general `_core` is considered private and you should avoid importing from there. If anything you require is missing from the public AnnData API, please open a ticket there and the devs will try to find a proper solution. 

We had similar issues with MuData today. 

### Minimal reproducible example

```python
import dandelion
```

### The error message produced by the code above

```pytb
>>> import dandelion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sturm/apps/micromamba/envs/test_scirpy/lib/python3.11/site-packages/dandelion/__init__.py", line 2, in <module>
    from dandelion import preprocessing as pp
  File "/home/sturm/apps/micromamba/envs/test_scirpy/lib/python3.11/site-packages/dandelion/preprocessing/__init__.py", line 2, in <module>
    from dandelion.preprocessing import external
  File "/home/sturm/apps/micromamba/envs/test_scirpy/lib/python3.11/site-packages/dandelion/preprocessing/external/__init__.py", line 2, in <module>
    from ._preprocessing import (
  File "/home/sturm/apps/micromamba/envs/test_scirpy/lib/python3.11/site-packages/dandelion/preprocessing/external/_preprocessing.py", line 17, in <module>
    from dandelion.utilities._utilities import *
  File "/home/sturm/apps/micromamba/envs/test_scirpy/lib/python3.11/site-packages/dandelion/utilities/__init__.py", line 3, in <module>
    from dandelion.utilities._io import *
  File "/home/sturm/apps/micromamba/envs/test_scirpy/lib/python3.11/site-packages/dandelion/utilities/_io.py", line 3, in <module>
    from dandelion.utilities._core import *
  File "/home/sturm/apps/micromamba/envs/test_scirpy/lib/python3.11/site-packages/dandelion/utilities/_core.py", line 16, in <module>
    from anndata._core.index import (
ImportError: cannot import name 'Index' from 'anndata._core.index' (/home/sturm/apps/micromamba/envs/test_scirpy/lib/python3.11/site-packages/anndata/_core/index.py)
```

**Comment by zktuong** [comment]
thanks @grst! will push a fix shortly
