### ISSUE TITLE
adjustText dependency missing

### ISSUE THREAD

**Issue by grst** [zktuong/dandelion#55]
Hi @zktuong, 

it seems you'll have to add the `adjusttext` dependency to your `setup.py`:

```
conda create -n test_dandelion python=3.8 pip
conda activate test_dandelion
pip install sc-dandelion
python -m dandelion
```

```pytb
Traceback (most recent call last):
  File "/home/sturm/anaconda3/envs/test_dandelion/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/sturm/anaconda3/envs/test_dandelion/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/sturm/anaconda3/envs/test_dandelion/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/sturm/anaconda3/envs/test_dandelion/lib/python3.8/site-packages/dandelion/__init__.py", line 10, in <module>
    from . import plotting as pl
  File "/home/sturm/anaconda3/envs/test_dandelion/lib/python3.8/site-packages/dandelion/plotting/__init__.py", line 7, in <module>
    from ._plotting import random_palette, clone_network, barplot, stackedbarplot, spectratype, clone_rarefaction, clone_overlap
  File "/home/sturm/anaconda3/envs/test_dandelion/lib/python3.8/site-packages/dandelion/plotting/_plotting.py", line 16, in <module>
    from adjustText import adjust_text
ModuleNotFoundError: No module named 'adjustText'
```

**Comment by zktuong** [comment]
Thanks @grst.

Currently my "installation instructions" is to do `conda install -c conda-forge distance joblib plotnine adjustText` 

I should test whether retrieving those via pypi would be sufficient and can simplify that.

**Comment by grst** [comment]
I see! Should be no problem retrieving those via `setup.py`.
